### ISSUE TITLE
Are WebSockets supported?

### ISSUE THREAD

**Issue by daPhantom** [electronicarts/orbit#1]
Are WebSockets supported as a Frontend solution?

I don't see any way for customers to interact with Java as Frontend in most web applications today. Besides that I would never build a web application which uses Java as Frontend since you will have an additional dependency which might not be available to the user.

**Comment by JoeHegarty** [comment]
Yes, websockets are indeed supported as a frontend by the default web container that is included in orbit.
The chat sample at samples/chat has an example of how to use websockets. See com.ea.orbit.samples.chat.ChatWebSocket in the chat-frontend project to see how it works.
