### ISSUE TITLE
Orbit vs Akka

### ISSUE THREAD

**Issue by Matzz** [electronicarts/orbit#102]
Hi,
I know that this is not the best place to ask such a questions but I didn't find a better one. Orbit seems to be a very interesting project. But I wonder why you created new library? I think Akka is already standard. So why Orbit?
What are pros (cons?) Orbit over Akka? Or maybe they address different problems?
I think such a information should be embedded into wiki/docs. I'm pretty sure that most of the people who first time see orbit already know something about Akka.

**Comment by DanielSperry** [comment]
Orbit implements Virtual Actors as proposed in the Orleans white paper.
It is a different abstraction from Akka actors.

For now I'll do the orbit side of the comparison:

Orbit:
- Actors are activated when you try to send a message to them.
- Actors are deactivated by timeout.
- Actor messages are defined as method calls.
- Orbit leverages CompletableFuture (`com.ea.orbit.Task`) to define async message handlers.
- You can use the `await` method, similar to the `await` keyword in c#.

**Comment by johnou** [comment]
@JoeHegarty maybe the documentation at http://orbit.bioware.com/orbit-actor-overview.html could be updated to include Daniel's list?

**Comment by JoeHegarty** [comment]
I've added a note to add this to our docs. I'll close this task out for now
