### ISSUE TITLE
Extending ActorProfiler to provide automatic thread dumps

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#119]
To debug "Missing counterpart (pending message) for message.." it might be desirable to extend the ActorProfile extension allowing for a configurable threshold in which if the execution time is exceeded the service automatically takes a thread dump to show what's blocking.. wdyt?

**Comment by DanielSperry** [comment]
I like it. 
I've done a similar thing in the past with the game frame rate. 
When there was a frame rate drop, the profiler would collect samples more frequently to help identify the cause of the drop.

A few things. 
* Currently the Actor profiler doesn't define the collection policy. It doesn't have a method to schedule the collection. 
* The "missing counterpart for message x" is issued in the caller node. It's the target node that needs to be profiled. So if stepping you the collection rate is desirable, an extension between Execution and Hosting would have to capture the incoming `Invocation`s and track the ones that are taking too long.

**Comment by johnou** [comment]
I'll try taking a look next sprint.

**Comment by DanielSperry** [comment]
cool :)
