### ISSUE TITLE
State Machine in Container: implementation glitch ? 

### ISSUE THREAD

**Issue by exercitussolus** [electronicarts/orbit#12]
This code: 

        catch (Throwable ex)
        {
            throw new UncheckedException(ex);
        }

in method Container.start() leaves the Container state in STARTING. Is that the intention ? Wouldn't we rather want to set the state back to CREATED before throwing the exception ?

**Comment by JoeHegarty** [comment]
Looks like the same is true in stop as well. Once there has been a failure the container there isn't a whole lot the framework can do other than expect the application/developer to take some action.

However, I agree the framework should not be left in an intermittent state and the behavior isn't correct.
I think the correct solution would be to introduce another state for error cases so it's clear to the application that the container is in an invalid state.

**Comment by exercitussolus** [comment]
Exactly. I teach UML classes, including State Machine diagrams. One of the
ground rules I and other colleagues always hammer into their heads: make
sure you have an ERROR state ( or FAILED, or whatever you call it ) you can
always reach from any state whose outgoing transitions may fail. From ERROR
/ FAILED, you'll prolly want to be able to reach both the INITIAL state (
in the case of Container: CREATED ), or an extra MAINTENANCE state.



*Fortuna audaces adiuvat - hos solos ? *

**Comment by JoeHegarty** [comment]
I've pushed a quick fix, thanks for pointing it out. 
I've also made a note to revisit this more closely and clean up the flow.
