### ISSUE TITLE
Question about using Servlets

### ISSUE THREAD

**Issue by amit2103** [electronicarts/orbit#120]
Hi All,
I had a simple query. Couldn't locate the docs (Sorry if it is there and I skipped it).
Can we use Jetty Servelts with Orbit ? Much liek we can use Websockets. 

Thanks

**Comment by JoeHegarty** [comment]
I'm not familiar with Jetty Servlets, but I don't see why not. 
The initialization code for Jetty is all contained in [EmbeddedHttpServer](https://github.com/electronicarts/orbit/blob/master/web/src/main/java/com/ea/orbit/web/EmbeddedHttpServer.java), you may need to make a change there to detect servlets as well, depending on how they work.

**Comment by DanielSperry** [comment]
@amit2103 we didn't make adding servlets to the orbit embedded web server straight forward because we never had a use case for it. 

Servlets are very low level compared to JAX-RS. What do you have in mind?

**Comment by DanielSperry** [comment]
I've added something that might help you with servlets:
check this change: https://github.com/electronicarts/orbit/commit/5af2ef7da5628d91a728710377ba8fb92faebec1

**Comment by amit2103** [comment]
@JoeHegarty  Thanks great.
@DanielSperry  Thanks...The last commit looks helpful...

We would mostly use JAXRS, but we thought of using Servlets for certain cornet cases where we are using so much of Request and Response objects directly that it does'nt make sense to keep using JAXRS.
