### ISSUE TITLE
Stop Orbit clustering

### ISSUE THREAD

**Issue by amit2103** [electronicarts/orbit#124]
Hi All,

Back with a question again. Thanks for the prompt answers on my other questions between. 
If I want orbit to stop discovering other instances what should I do/

Lets say I want to create 3 instances of Orbit , but I dont want them to auto discover each other, what should I do?

**Comment by JoeHegarty** [comment]
Orbit nodes will only cluster when the cluster name matches.
To create more than one cluster, you should change the orbit.actors.clusterName property.
You can do this in the orbit.yaml file if you are using container, or by calling .clusterName if you are using the stage builder.

**Comment by DanielSperry** [comment]
The easiest way is to use different cluster names.

If you are using orbit.yaml to configure your stage:

```
orbit.actors.clusterName: some-cluster-name
```

**Comment by amit2103** [comment]
@JoeHegarty  Thanks
