### ISSUE TITLE
Issues working with the IDE.

### ISSUE THREAD

**Issue by quilombodigital** [electronicarts/orbit#13]
I dont know if something is messed up in my setup, but something is strange.
cloned now, first time build with intellij.
"mvn clean install" with several exceptions. (showing success)
hello test did not worked from IDE, including .bat
chat did not worked from IDE, including .bat
"mvn clean install" more a couple of times.
chat worked using .bat, hello worked using .bat
hello main and hello test still dont work using run at the IDE.

Hum... I guess classpath search is showing the nonsense exceptions:
java.lang.ClassNotFoundException: sun/plugin2/util/ParameterNames
java.lang.ClassNotFoundException: com/sun/deploy/ui/DialogTemplate

The hello test error is:
ERROR com.ea.orbit.actors.runtime.Hosting - Error locating server for com.ea.orbit.samples.hello.IHello

[]s, Ricardo Mello (gandhi)

ps.: by the way the statelessworkertest sometimes fails at my machine with 5 and not 4.

**Comment by DanielSperry** [comment]
Hi gandhi, 

I'm glad to see you're testing Orbit.

About the tests you mentioned:

- The stateless test has been fixed now. Thanks for mentioning it.
- The exceptions from `mvn clean install` are from  `ExceptionalTest`. It tests exceptions and we see them in the logs. Normally there should be 3 of those exceptions.

About the issues you're having:
- Your problem might be that you're calling `mvn clean install` and then running things inside Intellij.
  You shouldn't need to call `mvn clean install` when using intellij. 
  Try instead running once `Build\Rebuild project`. 
  Then running HelloTest, or `com.ea.orbit.samples.hello.Main`.
- When running the .bat you usually need to have run maven first. 
  In most cases from the root dir of the project.

Please tell me how it goes, and I hope this helps.

**Comment by DanielSperry** [comment]
I saw your pull request, does it fix your issue?

**Comment by quilombodigital** [comment]
yes. Now the only classes being loaded are the correct ones. :)

**Comment by DanielSperry** [comment]
Great! Thanks for the contribution.
