### ISSUE TITLE
Task<T> vs Future<T>

### ISSUE THREAD

**Issue by jthelin** [electronicarts/orbit#2]
Hi Joe and team. Congratulations on your OSS release of the Orbit project. 

It is good to see more people understanding the importance of the actor paradigm for building scalable distributed systems :smile: 

I notice that Orbit Actor interfaces are defined using return type `Task<T>` to represent async promises. 
Could you provide some more insight into why you found that the `Future<T>` / `CompletableFuture<T>` types from core Java was not directly suitable for that purpose?

There is a little info in your docs, but I was just interested to understand the deeper design rational from your experiences.
http://orbit.bioware.com/orbit-actor-concept-tasks.html

Best wishes for your project's success, from a C# near-neighbor :wink: 

- Jorgen

**Comment by JoeHegarty** [comment]
Hi Jorgen,

There isn't really a single compelling reason that we decided to wrap CompletableFuture.
CF meets most of our needs but it was missing some simple things like extensions (such as fromValue) and we felt it was cleaner if working with async code was all performed via a single class.
We also wanted the flexibility to be able to control and change the API in future if we felt it was needed.

Hopefully that answers your question. 
Let me know if you have any other questions.

Joe

**Comment by jthelin** [comment]
Makes sense. Thanks for the prompt answer :)

**Comment by DanielSperry** [comment]
We also don't use Future<T> because it doesn't have all the nice async and composition methods that CompletableFuture and CompletionStage offer.

**Comment by DanielSperry** [comment]
That being said, we started the project having to write  `CompletableFuture<String> hello() { return CompletableFuture.completedFuture("hello"): }`

But it was so ugly that we decided to follow the lead from our c# friends on the Orleans side  :)
