### ISSUE TITLE
Code Formatter

### ISSUE THREAD

**Issue by quilombodigital** [electronicarts/orbit#22]
Please make available the intellij and eclipse code formatter files.
Another option would be to use a maven formatter plugin to format automatically.
I tested the maven-java-formatter (https://github.com/mblanchette/maven-java-formatter-plugin), but I did not liked the formatter config file to be replicated accross all projects.

[]s, Ricardo

**Comment by DanielSperry** [comment]
I've added the intellij settings to the project: https://github.com/electronicarts/orbit/commit/65383386f981a2167ac50dd18eb4bb8ac3e657f3

**Comment by quilombodigital** [comment]
Great! Thanks!

**Comment by DanielSperry** [comment]
I've also just added a preferences file for eclipse: https://github.com/electronicarts/orbit/commit/736f8d4c3b30d2e51f0675ae2deabcf6223ac7c3

It can be imported with `File \ Import` -> `General \ Preferences`
