### ISSUE TITLE
Very Long Actor Name Issue

### ISSUE THREAD

**Issue by quilombodigital** [electronicarts/orbit#38]
When using a very long actor name, the actor freezes in join().
When the actor is called alone, works ok, but when is called in conjunction with other actor methods, it freezes.

I have a example with the helloworld here:
https://github.com/quilombodigital/orbit/tree/longnameissue

**Comment by DanielSperry** [comment]
I've downloaded your branch. 
There is something happening there.

I just don't think it has anything to do with the length of the names.
I tested it with smaller names and the problem remains.

There are a few more thing to test. I'll work on it.

**Comment by DanielSperry** [comment]
It seems to be the suffix "*Tests".
Test it your self.

It might be related to JUnit... It needs more tests :p

**Comment by quilombodigital** [comment]
Happened with IOnlyIfActivatedExample and IOnlyIfActivatedExampleActor

**Comment by DanielSperry** [comment]
Fixed. Found a problem with the class path search.
The name of the class was related to the problem but not its size.

I've submitted a quick fix and will work more on it later.

**Comment by quilombodigital** [comment]
Great work! Thanks!
