### ISSUE TITLE
Timers violate actor thread safe guarantee

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#54]
Actor task methods and actor timer methods run in parallel, is this a feature or bug?

**Comment by JoeHegarty** [comment]
This is a bug, it violates the single-threaded guarantee on actors. 
A timer (and reminder, which we'll need to check) should really go through the same scheduling any other message does.

**Comment by johnou** [comment]
Can be reproduced by calling Thread.sleep in an actor task method and registering a timer in activateAsync with a low freq.

**Comment by DanielSperry** [comment]
This behaviour was intentional. 
We can change. But it's a bit hard to implement for stateless actors.

**Comment by johnou** [comment]
I've been able to easily code a workaround. Wanted to flag it, just incase.

**Comment by JoeHegarty** [comment]
Following the principle of least astonishment principal, I'd expect timers and reminders to honor the single-threaded guarantees.

A timer on a stateless worker doesn't make a whole lot of sense to me. It's inherently stateful to have the timer exist. If you register a timer on a stateless actor it makes logical sense that another instance might end up processing that timer, as that's the default behaviour of the framework.

**Comment by JoeHegarty** [comment]
It looks like Orleans is somewhere between just running it, and processing it immediately.
In their case, it's treated like the actor is reentrant.

Reentrancy is on our roadmap but my gut feeling is that it should be processed as a message.
Thoughts @johnou and @DanielSperry?

*Each invocation of asyncCallback is delivered to an activation on a separate turn and will never run concurrently with other turns on the same activation. Note however, asyncCallback invocations are not delivered as messages and are thus not subject to message interleaving semantics. This means that invocations of asyncCallback should be considered to behave as if running on a reentrant grain with respect to other messages to that grain.*

See: http://dotnet.github.io/orleans/Advanced-Concepts/Timers-and-Reminders

**Comment by DanielSperry** [comment]
Today the timer is a Callable, so it can capture variables from the actor and method that installed it.
Plus it can be a lambda. 
Turning it into a message will make it a bit more clumsy to call (as reminders are).

I think that if its behaviour is clear it could remain a Callable.

I've made it to return `Task` so it can use await directly. If we ensure that all Tasks interrupted during an actor execution serialize the callbacks, we can have the timers behaving as a messages.

**Comment by JoeHegarty** [comment]
I guess we'll need reentrancy before we can guarantee safety?

**Comment by JoeHegarty** [comment]
I'll close this one out for now, and add a note for us to review the behavior.
