### ISSUE TITLE
NPE for actor in default package

### ISSUE THREAD

**Issue by akiStudentKassel** [electronicarts/orbit#60]
If an actor is in the default package, NPE is thrown.

**Comment by JoeHegarty** [comment]
I've taken a quick look at this, we'll need to dig a little deeper to fix it.

For my own reference:

The crash happens in ActorFactoryGenerator.getFactoryFor.
The return for aInterface.getPackage is null (as expected), but it's further dereferenced with a getName() call.

It's not super obvious how to fix this as simply leaving the package name blank in that context causes Orbit to fail to find a server capable of processing the actor later on. We'll need to dig into how to ensure everywhere that touches the interfaces/actors understands that they could be in the default package.

**Comment by JoeHegarty** [comment]
Thanks @johnou 
This is fixed in #63 and will be in the 0.3.2 release once that is created.
