### ISSUE TITLE
Default parallelism too high

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#77]
By default Messaging and Execution will create their own ForkJoinPool with parallelism set to 1000, meaning that on a 64bit JRE (default thread stack size is 1 meg?) the JVM may use up to 2G of heap.

**Comment by JoeHegarty** [comment]
I agree it might make sense to drop this default, and make it configurable as part of the stage.

**Comment by JoeHegarty** [comment]
My proposal is that we merge the two execution pools we have currently (Messaging, Execution) into one pool, with a default pool size of 128, and allow this to be overridden by the application where appropriate.

**Comment by johnou** [comment]
Sounds good to me. I'd be interested in hearing @DanielSperry 's thoughts on using a single fjp for messaging and execution.

**Comment by DanielSperry** [comment]
I've made them separated because messaging unblocks execution.
So if all execution threads are blocked there would be no way (save timeout) to unblock them.

However that might be an overkill so.. what do you guys think?

**Comment by JoeHegarty** [comment]
I think I favor a single pool for clarity. In my mind, you essentially have a pool of threads that Orbit can use for whatever it needs.
It seems like 128 would be high enough for most applications, and allowing the application to tweak it if required seems like it would cover any cases where an application is both cpu intensive and high throughput.

**Comment by DanielSperry** [comment]
Cool by me. That could be a stage property.

**Comment by JoeHegarty** [comment]
Great. I'll go ahead and make this change this afternoon.

**Comment by JoeHegarty** [comment]
This is done in 
8f90177cabbbf184536ea9c27492fbc353306e9b
4937f009e0638d1536b17329e9110d52d6bf5764

**Comment by quilombodigital** [comment]
hum... I dont looked at the code, but I guess separated pools would be a better thing from my experience. In a system where you have direct connection between message and execution, this is ok, but I guess we are atalking about async messaging too. A huge boost of messages could took all the slots available for task processing, making the server just freeze processing, and make the message buffer worse. I prefer to guarantee it will keep processing at a minimum rate.

**Comment by quilombodigital** [comment]
In this sense, this could work like Seda, with minimum allocation and feedback from que queue sizes

**Comment by JoeHegarty** [comment]
My feeling is that the throughput would have to be so high before you'd get major contention between message processing and task execution that this wouldn't be a major concern. I'd be interested if there is a case where this is common though.

**Comment by quilombodigital** [comment]
Again, not looked at the code, but I assume that a bug in only one async call making it to block could cause this (one async method not returning, messages being stacked, threads being blocked)

**Comment by JoeHegarty** [comment]
I don't think that would occur as the pool is set at 128, so all threads would need to be blocked by that faulty message. Messages also time out after 30 seconds.

**Comment by johnou** [comment]
Obviously if all your threads are consumed / locked something is wrong but I am starting to lean towards the idea that in some scenarios two pools would increase throughput of messages / actor calls. Consider that if the execution of messages slows down and the threads back up the only thing which is going to free up the pool is the timeout where as having a second pool would allow for immediate unlocking of slow responses. If I am not mistaken one faulty message may lock multiple threads if using thenCompose..

**Comment by JoeHegarty** [comment]
Given the concern around this, I've resplit these pools but have left in place the ability to define the pool sizes easily.

See 8729e562cdbcbb38e28c3601100452fed08a7abb
