### ISSUE TITLE
Reflection invoked every time invoke is called in Execution

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#78]
As there is a large performance penalty with the use of reflection we should consider creating a singleton cache for annotation lookups.. https://github.com/electronicarts/orbit/commit/0ccba496b153164e04dcd0018aa1fda33c8876f4#diff-c8aa1f92453a884bb06ce94562693a7fR1212

**Comment by johnou** [comment]
# Fork: 1 of 1
# Warmup: 10 iterations, 1 s each
# Measurement: 10 iterations, 1 s each
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Running: com.ea.orbit.util.test.AnnotationUtilsTest.validateAnnotationCache
# Warmup Iteration   1: 4554.609 ops/ms
# Warmup Iteration   2: 5841.132 ops/ms
# Warmup Iteration   3: 6435.203 ops/ms
# Warmup Iteration   4: 6344.103 ops/ms
# Warmup Iteration   5: 6399.238 ops/ms
# Warmup Iteration   6: 6420.515 ops/ms
# Warmup Iteration   7: 6398.806 ops/ms
# Warmup Iteration   8: 6238.948 ops/ms
# Warmup Iteration   9: 6259.711 ops/ms
# Warmup Iteration  10: 6432.795 ops/ms
Iteration   1: 6439.464 ops/ms
Iteration   2: 6385.065 ops/ms
Iteration   3: 6354.809 ops/ms
Iteration   4: 6304.851 ops/ms
Iteration   5: 6378.160 ops/ms
Iteration   6: 6365.325 ops/ms
Iteration   7: 6450.577 ops/ms
Iteration   8: 6292.706 ops/ms
Iteration   9: 6352.279 ops/ms
Iteration  10: 6469.955 ops/ms

Result : 6379.319 ±(95%) 42.331 ±(99%) 60.821 ops/ms
  Statistics: (min, avg, max) = (6292.706, 6379.319, 6469.955), stdev = 59.179
  Confidence intervals: 95% [6336.988, 6421.650], 99% [6318.498, 6440.140]


# Fork: 1 of 1
# Warmup: 10 iterations, 1 s each
# Measurement: 10 iterations, 1 s each
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Running: com.ea.orbit.util.test.AnnotationUtilsTest.validateReflection
# Warmup Iteration   1: 2446.657 ops/ms
# Warmup Iteration   2: 2707.269 ops/ms
# Warmup Iteration   3: 2711.998 ops/ms
# Warmup Iteration   4: 2672.706 ops/ms
# Warmup Iteration   5: 2712.464 ops/ms
# Warmup Iteration   6: 2715.316 ops/ms
# Warmup Iteration   7: 2619.297 ops/ms
# Warmup Iteration   8: 2644.168 ops/ms
# Warmup Iteration   9: 2677.530 ops/ms
# Warmup Iteration  10: 2705.124 ops/ms
Iteration   1: 2714.140 ops/ms
Iteration   2: 2687.473 ops/ms
Iteration   3: 2715.665 ops/ms
Iteration   4: 2676.113 ops/ms
Iteration   5: 2704.872 ops/ms
Iteration   6: 2715.823 ops/ms
Iteration   7: 2705.450 ops/ms
Iteration   8: 2720.823 ops/ms
Iteration   9: 2687.831 ops/ms
Iteration  10: 2694.165 ops/ms

Result : 2702.235 ±(95%) 10.776 ±(99%) 15.482 ops/ms
  Statistics: (min, avg, max) = (2676.113, 2702.235, 2720.823), stdev = 15.064
  Confidence intervals: 95% [2691.460, 2713.011], 99% [2686.753, 2717.717]


Benchmark                                                 Mode Thr     Count  Sec         Mean   Mean error    Units
c.e.o.u.t.AnnotationUtilsTest.validateAnnotationCache    thrpt   1        10    1     6379.319       60.821   ops/ms
c.e.o.u.t.AnnotationUtilsTest.validateReflection         thrpt   1        10    1     2702.235       15.482   ops/ms
API replied benchmark score: 6379.319033333333 ops/ms over 10 iterations
API replied benchmark score: 2702.2352333333333 ops/ms over 10 iterations

**Comment by johnou** [comment]
https://github.com/electronicarts/orbit/pull/79

**Comment by JoeHegarty** [comment]
Thanks for the fix @johnou
