### ISSUE TITLE
Ability to return delayed Task / CompletableFuture

### ISSUE THREAD

**Issue by fixedorgo** [electronicarts/orbit#98]
Could you tell, is there a more simple way to create and return a delayed `Task`? Without such a construction:
```java
CompletableFuture<String> future = new CompletableFuture<>();
registerTimer(() -> {
    future.complete("bingo!");
    return Task.done();
}, 1000, 0, TimeUnit.MILLISECONDS);
return Task.fromFuture(future);
```
Have I something missed?
Thanks!

**Comment by JoeHegarty** [comment]
I believe this is the only way if you just want to wait a specific amount of time. While you're waiting for that though, the actor won't be able to process any further messages so using actor tasks for timing is not necessarily what you want.
What are you trying to achieve? There may be a better way.

**Comment by fixedorgo** [comment]
When we use regular scheduler we just set up when we want to send specific message (as a callback) to the specific actor. In `Orbit` we simply call the method and immediately obtain a callback in the form of Task (Future/Promise) that should be completed (or not) in the future. So, in this case: 
1. I'm unable to register timer and send message directly after some delay because we don't have messages as such.
2. Another way is to create `CompletableFuture`, give it back to the sender at once and complete it with timer after. But, as you said, this won't work (at least effectively).
3. And another way is to take reference of the sender and call necessary sender's method with a timer again. Something like:
```java
registerTimer(() -> sender.takeYourCallback("bingo!"), 1000, 0, TimeUnit.MILLISECONDS);
return Task.done();
```
I just need to delay some callback for the specific time period. For example, Akka has useful pattern `Patterns.after()` that returns `Future` (or run `Runnable`) after some timeout. How could I do this in `Orbit`?

**Comment by JoeHegarty** [comment]
If you want to delay a callback, I think the correct way would be as you are showing in 3. 
You can achieve the effect of sending a message by using Actor.getReference or you can use the sender interface like in your example.

```java
Task doSomeCallback(SomeActorInterface sender, String message)
{
    registerTimer(() -> sender.takeYourCallback(message), 1000, 0, TimeUnit.MILLISECONDS);
}
```

```java
Task doSomeCallback(String callbackId, String message)
{
    registerTimer(() -> Actor.getReference(SomeActorInterface.class, callbackId).takeYourCallback(message), 1000, 0, TimeUnit.MILLISECONDS);
}
```

Timers do not respect the usual interleaving rules that messages do, so that's something to be aware of (they will run in parallel to messages being processed). Because of that, the approach of getting a reference and sending a message (even for your own actor) often makes sense.

**Comment by quilombodigital** [comment]
hum... I guess it should be possible to implement a custom annotation
too...

2015-08-23 19:56 GMT-03:00 Joe Hegarty <notifications@github.com>:

**Comment by fixedorgo** [comment]
Thank you, Joe! I will try. But, quite possible, that this is some kind of anti-pattern in such architecture. There could be another way to schedule callbacks without thread blocking.

**Comment by JoeHegarty** [comment]
In the case of your latter example, it won't actually block the thread as you are returning Task.done() to the caller, so the task will complete immediately and execution will unblock the thread. Then your timer will execute outside the context of the execution of that actor. So, when you call the sender with the callback that's just going to send a message from outside the actor's context.

I think that satisfies your use case without causing undue blocking (the initial issue was that you were returning the future/task that the timer would eventually complete, which would cause execution to stop processing messages on that actor as it was still "processing" the last message/call).

**Comment by JoeHegarty** [comment]
I'll close this one off for now. Please feel free to continue the discussion or re-open it if you have any questions with my last response.
